[package]
name = "day05"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]
edition = "2018"

[dependencies]
# log = "0.4"
anyhow = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
criterion = "0.3"
env_logger = "0.8"

[[bench]]
name = "aoc_benchmark"
harness = false
