name: Rust

on: [push]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
  documentation:
    name: Deploy documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Build documentation
        run: cargo doc --no-deps
      - name: Post-process documentation
        run: |
          mkdir public
          cp -r target/doc/* public/
          # Copy benchmark information
          for day in day*; do cp -r ${day}/target/criterion/* public/${day}; done
          # Adapt links from docs to benchmark information
          for day in day*; do sed "s|../../../${day}/target/criterion/||g" -i public/${day}/index.html; done
          echo "<meta http-equiv=refresh content=0;url=day01/index.html>" > public/index.html
      - name: GitHub Pages Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
